SELECT
		 NULL AS "Contact ID",
		 NULL AS "First Name",
		 NULL AS "Last Name",
		 NULL AS "Annual Revenue",
		 NULL AS "Associated Company ID",
		 NULL AS "Company Name",
		 NULL AS "Country/Region",
		 NULL AS "Contact owner",
		 NULL AS "Branche",
		 NULL AS "Associated Deals",
		 NULL AS "Lifecycle Stage",
		 NULL AS "Lead Status",
		 "Date",
		 NULL AS "Email",
		 NULL AS "Phone Number",
		 NULL AS "Became a Lead Date",
		 NULL AS "Website URL",
		 NULL AS "Create Date",
		 NULL AS "Became a Marketing Qualified Lead Date",
		 NULL AS "Original Source Label",
		 NULL AS "Became a Sales Qualified Lead Date",
		 NULL AS "Became a Subscriber Date",
		 NULL AS "Became an Opportunity Date",
		 NULL AS "Became an Evangelist Date",
		 NULL AS "Original Source",
		 NULL AS "Close Date",
		 NULL AS "HubSpot Score",
		 NULL AS "City",
		 NULL AS "Number of Associated Deals",
		 NULL AS "State/Region",
		 NULL AS "Total Revenue"
FROM  "DateTable" /* This is a sample SQL SELECT Query */
/*Use "Control + Space Bar" to see other keywords*/ 
