"Contact ID",
"First Name",	
"Last Name", 
"Annual Revenue",
"Associated Company ID",
"Company Name",
"Country/Region",
"Contact owner",
"Branche",
"Associated Deals",
"Lifecycle Stage",
"Lead Status",
-- "Became a Customer Date",
"Email",
"Phone Number",
-- "Became a Lead Date",
"Website URL",
-- "Create Date",
-- "Became a Marketing Qualified Lead Date",
"Original Source Label",
-- "Became a Sales Qualified Lead Date",
-- "Became a Subscriber Date",
-- "Became an Opportunity Date",
-- "Became an Evangelist Date",
"Original Source",
-- "Close Date" ,
"HubSpot Score",
"City",
"Number of Associated Deals",
"State/Region",
"Total Revenue",