 "Date",
"First Name",
"Last Name",
"Company Name",
"Company ID",
"Annual Revenue",
"Website URL",
"Number of Employees",
"Industry",
"Country/Region",
"City",
"Business Value",
"Contact owner",
"Branche",
"Associated Deals",
"Lifecycle Stage",
"Lead Status",
"Email",
"Phone Number",
"Original Source",
"HubSpot Score",
"Number of Associated Deals",
"State/Region",
"Total Revenue",
"Became a Customer Date",
"Became a Lead Date",
"Create Date",
"Became a Marketing Qualified Lead Date",
"Became a Sales Qualified Lead Date",
"Became a Subscriber Date",
"Became an Opportunity Date",
"Became an Evangelist Date",	
"Close Date"