SELECT
0 AS "Date",
"Contact ID",
"First Name",	
"Last Name", 
"Annual Revenue",
"Associated Company ID",
"Company Name",
"Country/Region",
"Contact owner",
"Branche",
"Associated Deals",
"Lifecycle Stage",
"Lead Status",
"Became a Customer Date",
"Email",
"Phone Number",
"Became a Lead Date",
"Website URL",
"Create Date",
"Became a Marketing Qualified Lead Date",
"Original Source Label",
"Became a Sales Qualified Lead Date",
"Became a Subscriber Date",
"Became an Opportunity Date",
"Became an Evangelist Date",
"Original Source",
"Close Date" ,
"HubSpot Score",
"City",
"Number of Associated Deals",
"State/Region",
"Total Revenue"
FROM "Contacts (HubSpot CRM)" 
UNION ALL
SELECT
"Date",
0 AS "Contact ID",
0 AS "First Name",	
0 AS "Last Name", 
0 AS "Annual Revenue",
0 AS "Associated Company ID",
0 AS "Company Name",
0 AS "Country/Region",
0 AS "Contact owner",
0 AS "Branche",
0 AS "Associated Deals",
0 AS "Lifecycle Stage",
0 AS "Lead Status",
0 AS "Became a Customer Date",
0 AS "Email",
0 AS "Phone Number",
0 AS "Became a Lead Date",
0 AS "Website URL",
0 AS "Create Date", 
0 AS "Became a Marketing Qualified Lead Date",
0 AS "Original Source Label",
0 AS "Became a Sales Qualified Lead Date",
0 AS "Became a Subscriber Date",
0 AS "Became an Opportunity Date",
0 AS "Became an Evangelist Date",
0 AS "Original Source",
0 AS "Close Date" ,
0 AS "HubSpot Score",
0 AS "City",
0 AS "Number of Associated Deals",
0 AS "State/Region",
0 AS "Total Revenue" 
FROM "DateTable"  

