SELECT
		 "Date",
		 "Companies (HubSpot CRM)"."Company ID" AS "Company ID (Companies)",
		 "Companies (HubSpot CRM)"."Company Name" AS "Company Name (Companies)",
		 "Companies (HubSpot CRM)"."Number of Associated Contacts" AS "Number of Associated Contacts (Companies)",
		 "Companies (HubSpot CRM)"."Annual Revenue" AS "Annual Revenue (Companies)",
		 "Companies (HubSpot CRM)"."Website URL" AS "Website URL (Companies)",
		 "Companies (HubSpot CRM)"."Number of Employees" AS "Number of Employees (Companies)",
		 "Companies (HubSpot CRM)"."Industry" AS "Industry (Companies)",
		 "Companies (HubSpot CRM)"."Country/Region" AS "Country/Region (Companies)",
		 "Companies (HubSpot CRM)"."State/Region" AS "State/Region (Companies)",
		 "Companies (HubSpot CRM)"."City" AS "City (Companies)",
		 "Companies (HubSpot CRM)"."Business Value" AS "Business Value (Companies)",
		 "Companies (HubSpot CRM)"."Lead Status" AS "Lead Status (Companies)",
		 "Companies (HubSpot CRM)"."Lifecycle Stage" AS "Lifecycle Stage (Companies)",
		 "Companies (HubSpot CRM)"."Target Account" AS "Target Account (Companies)",
		 "Companies (HubSpot CRM)"."Ideal Customer Profile Tier" AS "ICP (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Abonnent (Lifecycle Stage Pipeline)'" AS "Became SUB (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Lead (Lifecycle Stage Pipeline)'" AS "Became LEAD (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Marketing-Qualified-Lead (Lifecycle Stage Pipeline)'" AS "Became MQL (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Sales-Qualified-Lead (Lifecycle Stage Pipeline)'" AS "Became SQL (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Opportunity (Lifecycle Stage Pipeline)'" AS "Became OPP (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Kunde (Lifecycle Stage Pipeline)'" AS "Became CUS (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Partner (Lifecycle Stage Pipeline)'" AS "Became PARTNER (Companies)",
		 "Companies (HubSpot CRM)"."Date entered 'Sonstiges (Lifecycle Stage Pipeline)'" AS "Became ELSE (Companies)",
		 "Companies (HubSpot CRM)"."Original Source Type" AS "Original Source Type (Companies)",
		 "Companies (HubSpot CRM)"."Original Source Data 1" AS "Original Source Data 1 (Companies)",
		 "Companies (HubSpot CRM)"."Original Source Data 2" AS "Original Source Data 2 (Companies)",
		 "Processed: all phases (Contacts)"."Primary Associated Company ID" AS "Company ID (Contacts)",
		 "Processed: all phases (Contacts)"."Last Name" AS "Last Name (Contacts)",
		 "Processed: all phases (Contacts)"."First Name" AS "First Name (Contacts)",
		 "Processed: all phases (Contacts)"."Contact owner" AS "Contact owner (Contacts)",
		 "Processed: all phases (Contacts)"."Branche" AS "Branche (Contacts)",
		 "Processed: all phases (Contacts)"."Associated Deals" AS "Associated Deals (Contacts)",
		 "Processed: all phases (Contacts)"."Lifecycle Stage" AS "Lifecycle Stage (Contacts)",
		 "Processed: all phases (Contacts)"."Lead Status" AS "Lead Status (Contacts)",
		 "Processed: all phases (Contacts)"."Email" AS "Email (Contacts)",
		 "Processed: all phases (Contacts)"."Phone Number" AS "Phone Number (Contacts)",
		 "Processed: all phases (Contacts)"."Original Source" AS "Original Source (Contacts)",
		 "Processed: all phases (Contacts)"."HubSpot Score" AS "HubSpot Score (Contacts)",
		 "Processed: all phases (Contacts)"."Number of Associated Deals" AS "Numb of Associated Deals (Contacts)",
		 "Processed: all phases (Contacts)"."State/Region" AS "State/Region (Contacts)",
		 "Processed: all phases (Contacts)"."Total Revenue" AS "Total Revenue (Contacts)",
		 "Processed: all phases (Contacts)"."Became a Subscriber Date" AS "Became SUB (Contacts)",
		 "Processed: all phases (Contacts)"."Became a Lead Date" AS "Became LEAD (Contacts)",
		 "Processed: all phases (Contacts)"."Became a Marketing Qualified Lead Date" AS "Became MQL (Contacts)",
		 "Processed: all phases (Contacts)"."Became a Sales Qualified Lead Date" AS "Became SQL (Contacts)",
		 "Processed: all phases (Contacts)"."Became an Opportunity Date" AS "Became OPP (Contacts)",
		 "Processed: all phases (Contacts)"."Became a Customer Date" AS "Became CUS (Contacts)",
		 "Processed: all phases (Contacts)"."Became an Evangelist Date" AS "Became EVA (Contacts)"
FROM  "Processed: all phases (Contacts)"
JOIN "Companies (HubSpot CRM)" ON "Processed: all phases (Contacts)"."Primary Associated Company ID"  = "Companies (HubSpot CRM)"."Company ID"  
