SELECT
		 "Processed: CUS (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: CUS (companies)" 
UNION ALL
 SELECT
		 "Processed: LEAD (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: LEAD (companies)" 
UNION ALL
 SELECT
		 "Processed: SUB (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: SUB (companies)" 
UNION ALL
 SELECT
		 "Processed: MQL (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: MQL (companies)" 
UNION ALL
 SELECT
		 "Processed: OPP (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: OPP (companies)" 
UNION ALL
 SELECT
		 "Processed: EVA (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: EVA (companies)" 
UNION ALL
 SELECT
		 "Processed: SQL (companies)"."Date" AS "Date",
		 "Company ID",
		 "Company name",
		 "Annual Revenue",
		 "Associated Contacts",
		 "Associated Deals",
		 "Business Value",
		 "City",
		 "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 "SQL",
		 NULL AS "Sonstiges",
		 "Ideal Customer Profile Tier",
		 "Industry",
		 "Last Activity Date",
		 "Last Contacted",
		 "Last Modified Date",
		 "Lead Gen Quelle",
		 "Lead Status",
		 "Lifecycle Stage",
		 "Next Activity Date",
		 "Number of Associated Contacts",
		 "Number of Associated Deals",
		 "Number of Employees",
		 "Original Source Data 1",
		 "Original Source Data 2",
		 "Original Source Type",
		 "Postal Code",
		 "State/Region",
		 "Target Account",
		 "Target Account Probability",
		 "Total Money Raised",
		 "Total open deal value",
		 "Total Revenue",
		 "Website URL",
		 NULL AS "Planned Lead",
		 NULL AS "Planned MQL",
		 NULL AS "Planned SQL",
		 NULL AS "Planned OPP",
		 NULL AS "Planned Customer"
FROM  "Processed: SQL (companies)" 
UNION ALL
 SELECT
		 "Config: Sales KPI"."Date" AS "Date",
		 NULL AS "Company ID",
		 NULL AS "Company name",
		 NULL AS "Annual Revenue",
		 NULL AS "Associated Contacts",
		 NULL AS "Associated Deals",
		 NULL AS "Business Value",
		 NULL AS "City",
		 NULL AS "Country/Region",
		 NULL AS "Customer",
		 NULL AS "Close Date",
		 NULL AS "Create Date",
		 NULL AS "Subscriber",
		 NULL AS "Lead",
		 NULL AS "MQL",
		 NULL AS "OPP",
		 NULL AS "Partner",
		 NULL AS "SQL",
		 NULL AS "Sonstiges",
		 NULL AS "Ideal Customer Profile Tier",
		 NULL AS "Industry",
		 NULL AS "Last Activity Date",
		 NULL AS "Last Contacted",
		 NULL AS "Last Modified Date",
		 NULL AS "Lead Gen Quelle",
		 NULL AS "Lead Status",
		 NULL AS "Lifecycle Stage",
		 NULL AS "Next Activity Date",
		 NULL AS "Number of Associated Contacts",
		 NULL AS "Number of Associated Deals",
		 NULL AS "Number of Employees",
		 NULL AS "Original Source Data 1",
		 NULL AS "Original Source Data 2",
		 NULL AS "Original Source Type",
		 NULL AS "Postal Code",
		 NULL AS "State/Region",
		 NULL AS "Target Account",
		 NULL AS "Target Account Probability",
		 NULL AS "Total Money Raised",
		 NULL AS "Total open deal value",
		 NULL AS "Total Revenue",
		 NULL AS "Website URL",
		 "Planned Lead",
		 "Planned MQL",
		 "Planned SQL",
		 "Planned OPP",
		 "Planned Customer"
FROM  "Config: Sales KPI" 
 
 
 
 
 
 
 
